# Generated by Django 5.2.17 on 2026-09-29 23:58

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assts/favicon/%Y/%m/', validators=[utils.model_validators.validate_png]),
        ),
    ]
